export const USER_REQUESTED = "USER_REQUESTED";
export const USER_FETCHED = "USER_FETCHED";
export const REQUEST_USER_FAILED = "REQUEST_USER_FAILED";
export const REPO_LIST_FETCHED = "REPO_LIST_FETCHED";
export const REPO_FETCHED = "REPO_FETCHED";
export const CHANGE_SORT_REPOS = "CHANGE_SORT_REPOS";
export const CHANGE_REPOS_PAGE = "CHANGE_REPOS_PAGE";
